### ISSUE TITLE
npm version does not work with React 18

### ISSUE THREAD

**Issue by nikwen** [lhansford/react-to-text#281]
Thank you so much for this amazing package! 🙌 I use it to fill the description meta tag on the subpages of my interactive terminal tutorial at https://www.terminaltutor.com.

## The issue

The version that's published on npm is >1 year old and it still requires react `^17.0.2`.

Installing with React 18 fails with the following error:

```
Could not resolve dependency:
peer react@"^17.0.2" from react-to-text@1.1.0
```

This is fixed in the repo but the change has not yet been published to npm.

Would it be possible to publish an updated package to npm?

## Workaround

For now you can install the package from the GitHub repo by adding the following to your `package.json`:

```
  "dependencies": {
    "react-to-text": "git://github.com/lhansford/react-to-text.git#c5f8120fa087bb61b568086824c63589e69fb63c"
  }
```

Replace the commit hash at the end to install from a different commit.

**Comment by lhansford** [comment]
Hey @nikwen. Glad you're getting some use from the package! I'll take a look at getting the dependencies up to date and releasing it.

**Comment by lhansford** [comment]
I've updated that now, version 2.0.1 should hopefully work for you. Let me know if it doesn't and I'll take a further look.

**Comment by nikwen** [comment]
Wow, Luke! That was super fast. Thank you so much!

Just updated the package to the npm version and everything works perfectly. Really appreciate your help.

**Comment by lhansford** [comment]
No worries!
